# Site Info
title:              "Ryan"
description:        "Investor | Plan-Based | Ultrarunner"
author_name:        "Ryan" # change this to your name
logo_url:           https://avatars.githubusercontent.com/u/105316296?s=400&u=d9f631e3436c5d8bb6340e993d08a9a150a12ed0&v=4
# Site Settings
url:                https://ryanmhopkins.com # main url
baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           America/LosAngeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
